name: libcap
builder:
  name: BalabitBuilder
  flags: "no-configure no-local-build no-make-dist"
platforms:
  - linux-glibc2.3.6/amd64
  - linux-glibc2.3.6/i386
  - linux-glibc2.11/amd64
  - linux-glibc2.11/i386
